### PR TITLE
Try resolving local node-gyp before global

### PR DESCRIPTION
**Pull request by emilbayes**

### CODE REVIEW

**Comment by emilbayes** [comment]
Yeah, so this doesn't resolve as I wanted it

**Comment by emilbayes** [comment]
Maybe this could be used? https://github.com/timoxley/npm-which

**Comment by ralphtheninja** [comment]
> Maybe this could be used? https://github.com/timoxley/npm-which

Seems very old and not maintained. Didn't @mafintosh do something with resolving these paths lately? (Vague memory).

**Comment by mafintosh** [comment]
We merged in #12 based on the learnings here.

**Pull request closed without merging**
