### PR TITLE
allow injecting a prebuild using an env var

### PR DESCRIPTION
**Pull request by mafintosh**

### CODE REVIEW

**Comment by emilbayes** [comment]
Good enough for now :)

**Comment by jimpick** [comment]
This is working for me for the iOS build of cabal-mobile...

https://github.com/jimpick/cabal-mobile/tree/ios

**Comment by mafintosh** [comment]
@jimpick added a check in the build-test where it always skips building if the env is set

**Comment by mafintosh** [comment]
3.4.0

**Pull request merged**
