### PR TITLE
spawn local node-gyp directly

### PR DESCRIPTION
**Pull request by mafintosh**
Simpler alternative to https://github.com/mafintosh/node-gyp-build/pull/11 (needs testing)

### CODE REVIEW

**Comment by emilbayes** [comment]
Only reservation is that this only works for direct dependencies. Theoretically this would break if two dependencies had conflicting `node-gyp`s

**Comment by emilbayes** [comment]
Verification that this works: https://travis-ci.org/sodium-friends/sodium-native/builds/465924070

**Comment by mafintosh** [comment]
@emilbayes re, https://github.com/mafintosh/node-gyp-build/pull/12#issuecomment-445776679, define breakage :D it would just find the closest one to node-gyp-build

**Comment by emilbayes** [comment]
So the linked `node-gyp.cmd` is not required on windows? Because then this is perfect. However the build above ran in Git bash shell

**Comment by emilbayes** [comment]
This build will tell: https://ci.appveyor.com/project/mafintosh/sodium-native/builds/20893741

**Pull request merged**
